name: zen
version: 1.0.0-alpha
descritpion: Build `html_builder` nodes by writing CSS selectors.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/thosakwe/zen
environment:
  sdk: ">=1.19.0"
dependencies:
  csslib: ^0.14.0
  html_builder: ^1.0.0
dev_dependencies:
  test: ^0.12.0